#
# This file is part of research-processing library
# Copyright (C) 2021 INPE.
#
# research-processing is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: '3.2'

services:
  research-processing-notebook:
    user: ${UID}:${GID}
    build:
      context: .
      dockerfile: docker/notebook/Dockerfile
    image: research-processing-notebook:0.1
    container_name: research-processing-notebook
    environment:
      - DATA_DIRECTORY=${PWD}/analysis/data
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ${PWD}/analysis/
        target: /home/jovyan/analysis
      - type: bind
        source: ${PWD}/analysis/data
        target: ${PWD}/analysis/data
    ports:
      - "8888:8888"
    env_file:
      - .env
    restart: on-failure
    networks:
      - research-processing-network

networks:
  research-processing-network:
    external: true
