#
# This file is part of c-factor library
# Copyright (C) 2021 INPE.
#
# c-factor is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: '3.2'

services:
  cfactor-notebook:
    user: ${UID}:${GID}
    build:
      context: .
      dockerfile: docker/notebook/Dockerfile
    image: cfactor-notebook:0.1
    container_name: cfactor-notebook
    environment:
      - CFACTOR_DATA_DIRECTORY=${PWD}/analysis/data
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ${PWD}/analysis/
        target: /home/jovyan/cfactor-analysis
      - type: bind
        source: ${PWD}/analysis/data
        target: ${PWD}/analysis/data
    ports:
      - "8888:8888"
    env_file:
      - .env
    restart: on-failure
    networks:
      - cfactor_network

networks:
  cfactor_network:
    external: true
