name: base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.0
  - alsa-lib=1.2.3
  - anyio=3.3.4
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=4.1.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cryptography=35.0.0
  - curl=7.78.0
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.1
  - importlib-metadata=4.8.1
  - intel-openmp=2020.2
  - ipykernel=6.4.2
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.2
  - jpeg=9d
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=4.1.2
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - jupyter_server=1.11.2
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libclang=11.1.0
  - libcurl=7.78.0
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgdal=3.3.1
  - libgfortran-ng=7.3.0
  - libglib=2.68.3
  - libgomp=9.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libogg=1.3.4
  - libopenblas=0.3.10
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.8.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_random=1.1.0
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nbclassic=0.3.4
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.5
  - nspr=4.30
  - nss=3.67
  - numexpr=2.7.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.2
  - pandoc=2.16
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.4
  - pixman=0.40.0
  - poppler=21.03.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.0.1
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.21
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyzmq=19.0.2
  - qt=5.12.9
  - rasterio=1.2.6
  - readline=8.1
  - requests=2.26.0
  - send2trash=1.8.0
  - setuptools=58.0.4
  - shapely=1.7.1
  - six=1.15.0
  - sniffio=1.2.0
  - snuggs=1.4.7
  - sqlite=3.36.0
  - terminado=0.12.1
  - testpath=0.5.0
  - tiledb=2.3.2
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - tzcode=2021a
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - charset-normalizer==2.0.7
    - docker==5.0.0
    - idna==3.3
    - websocket-client==1.2.1
