#
# This file is part of Brazil Data Cube compendium-harmonization.
# Copyright (C) 2022 INPE.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
#

version: "3.2"

services:
  example-build-environment:
    build:
      context: .
    image: harmonization-compendium/tools-upload-assets_piggyback:0.1
    container_name: tools-upload-assets_piggyback
    environment:
      #
      # 1. GitHub configurations.
      #
      - GITHUB_TOKEN=
      - GITHUB_TAGNAME=
      - GITHUB_REPOSITORY=

      #
      # 2. Directories where the files that should be uploaded to GitHub assets are stored
      #
      - MINIMAL_EXAMPLE_DIRECTORY=/opt/compendium/example-files
      - REPLICATION_EXAMPLE_DIRECTORY=/opt/compendium/replication-files
    volumes:
      #
      # 3. Volume with the directory where the zip and checksum files of the minimum example are.
      # 
      - type: bind
        source: /path/to/example/zip/files
        target: /opt/compendium/example-files  # same defined on `MINIMAL_EXAMPLE_DIRECTORY` variable

      #
      # 4. Volume with the directory where the zip and checksum files of the minimum example are.
      # 
      - type: bind
        source: /path/to/replication/zip/files
        target: /opt/compendium/replication-files  # same defined on `REPLICATION_EXAMPLE_DIRECTORY` variable

    networks:
      - research_processing_network

networks:
  research_processing_network:
    external: true
