#
# This file is part of Brazil Data Cube compendium-harmonization.
# Copyright (C) 2022 INPE.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
#

version: "3.2"

services:
  example-replication-notebook:

    user: ${UID}:${GID}
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/notebook/Dockerfile
    image: brazildatacube/research-processing-jupyter:latest
    container_name: example-replication-notebook

    environment:
      #
      # 1. Enable Jupyter Lab (https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options)
      #
      - JUPYTER_ENABLE_LAB=yes

      #
      # 2. Path to the directory where the data is stored on the local machine (Default is the minimal example directory).
      #
      - DATA_DIRECTORY=${PWD}/analysis/data/examples/replication_example

    volumes:

      #
      # 3. Volume that enable docker usage inside the container.
      #
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

      #
      # 4. Volume to mapping the compendium `analysis` directory to the user workspace inside the container.
      #
      - type: bind
        source: ${PWD}/analysis/
        target: /home/jovyan/analysis

    ports:

      #
      # 6. Network port to access the JupyterLab web interface.
      #
      - "8888:8888"

    env_file:

      #
      # 7. Environment variables file to define the UID and GID used inside the container.
      #
      - .env

    restart: on-failure
    networks:
      - research_processing_network

networks:
  research_processing_network:
    external: true
